#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include "drivers/telemetry_protocol.hpp"
#include "hal/mock/hal_uart_mock.hpp"
#include "util/crc16.hpp"

using ::testing::_;
using ::testing::Return;
using ::testing::NiceMock;
using ::testing::ElementsAre;

// Test fixture: creates a fresh mock before each test.
// NiceMock = doesn't warn on unexpected mock calls.
class TelemetryProtocolTest : public ::testing::Test {
protected:
    NiceMock<hal::mock::MockUart> mock_uart;
};

// Test 1: init() must return false if UART hardware init fails.
TEST_F(TelemetryProtocolTest, InitFailsWhenUartInitFails) {
    // Arrange: mock returns HW_ERROR when init is called
    EXPECT_CALL(mock_uart, init(hal::IUart::BaudRate::BAUD_115200))
        .WillOnce(Return(hal::Status::HW_ERROR));

    // Act
    drivers::TelemetryProtocol proto(mock_uart);

    // Assert
    EXPECT_FALSE(proto.init());
}

// Test 2: send_frame must reject payloads larger than MAX_PAYLOAD.
TEST_F(TelemetryProtocolTest, RejectsOversizedPayload) {
    // Arrange: init succeeds
    EXPECT_CALL(mock_uart, init(_))
        .WillOnce(Return(hal::Status::OK));

    drivers::TelemetryProtocol proto(mock_uart);
    ASSERT_TRUE(proto.init());  // ASSERT: if init fails, stop test here

    // Act: try to send MAX_PAYLOAD + 1 bytes
    std::array<uint8_t, drivers::TelemetryProtocol::MAX_PAYLOAD + 1> payload{};

    // Assert
    EXPECT_FALSE(proto.send_frame(payload.data(), payload.size()));
}

// Test 3: send_frame succeeds when UART init OK and transmit OK
TEST_F(TelemetryProtocolTest, SendFrameTransmitsCorrectByteSequence) {
    // Arrange - 1. Config Init
    EXPECT_CALL(mock_uart, init(_))
        .WillOnce(Return(hal::Status::OK));
    drivers::TelemetryProtocol proto(mock_uart);
    ASSERT_TRUE(proto.init());

    // 2. Example payload
    const uint8_t payload[] = {0x42, 0xAB, 0xCD};
    
    // Manual compute CRC over: LEN (0x03) + PAYLOAD (0x42, 0xAB, 0xCD)
    uint8_t crc_data[] = {0x03, 0x42, 0xAB, 0xCD};
    uint16_t expected_crc = util::crc16_ccitt(crc_data, 4); 
    uint8_t crc_hi = static_cast<uint8_t>(expected_crc >> 8);
    uint8_t crc_lo = static_cast<uint8_t>(expected_crc & 0xFF);

    // Act - 3. EXPECT_CALL: Capture and inspect the bytes sent
    // We verified that transmit is called with a length of 7 bytes (1+1+3+2)
    EXPECT_CALL(mock_uart, transmit(_, 7, 1000))
        .WillOnce([crc_hi, crc_lo](const uint8_t* data, [[maybe_unused]] std::size_t len, [[maybe_unused]] uint32_t timeout) {
            // We evaluate byte by byte the temporary buffer generated by the driver
            EXPECT_EQ(data[0], 0xAA);        // SOF
            EXPECT_EQ(data[1], 0x03);        // LEN
            EXPECT_EQ(data[2], 0x42);        // Payload 0
            EXPECT_EQ(data[3], 0xAB);        // Payload 1
            EXPECT_EQ(data[4], 0xCD);        // Payload 2
            EXPECT_EQ(data[5], crc_hi);      // CRC MSB
            EXPECT_EQ(data[6], crc_lo);      // CRC LSB
            
            return hal::Status::OK;
        });

    // 4. Act & Assert
    EXPECT_TRUE(proto.send_frame(payload, sizeof(payload)));
}


// Test 4: send_frame fails if UART transmit returns TIMEOUT.
TEST_F(TelemetryProtocolTest, SendFrameFailsOnTransmitTimeout) {
    EXPECT_CALL(mock_uart, init(_))
        .WillOnce(Return(hal::Status::OK));
    EXPECT_CALL(mock_uart, transmit(_, _, _))
        .WillOnce(Return(hal::Status::TIMEOUT));

    drivers::TelemetryProtocol proto(mock_uart);
    ASSERT_TRUE(proto.init());

    const uint8_t payload[] = {0x01};
    EXPECT_FALSE(proto.send_frame(payload, sizeof(payload)));
}

// Test 5: send_frame fails if not initialized. FSM Tx Validation.
TEST_F(TelemetryProtocolTest, SendFrameFailsIfNotInitialized) {
    // No EXPECT_CALL needed: if init() wasn't called, transmit should never be called.
    // StrictMock would catch this, but our guard clause returns false before calling transmit.

    drivers::TelemetryProtocol proto(mock_uart);
    const uint8_t payload[] = {0x01};
    EXPECT_FALSE(proto.send_frame(payload, sizeof(payload)));
}

// Edge-case Test 6: send_frame with zero-length payload should still transmit SOF+LEN+CRC
TEST_F(TelemetryProtocolTest, SendFrameEmptyPayload) {
    EXPECT_CALL(mock_uart, init(_))
        .WillOnce(Return(hal::Status::OK));
    EXPECT_CALL(mock_uart, transmit(_, 4, 1000))  // SOF(1)+LEN(1)+CRC(2) = 4
        .WillOnce([](const uint8_t* data, std::size_t /* len */, uint32_t) {
            EXPECT_EQ(data[0], 0xAA);    // SOF
            EXPECT_EQ(data[1], 0x00);    // LEN = 0
            uint16_t expected_crc = util::crc16_ccitt(&data[1], 1);  // CRC over [0x00]
            EXPECT_EQ(data[2], static_cast<uint8_t>(expected_crc >> 8));
            EXPECT_EQ(data[3], static_cast<uint8_t>(expected_crc & 0xFF));
            return hal::Status::OK;
        });

    drivers::TelemetryProtocol proto(mock_uart);
    ASSERT_TRUE(proto.init());
    EXPECT_TRUE(proto.send_frame(nullptr, 0));
}

// Edge-case Test 7: send_frame with max payload (64 bytes) boundary
TEST_F(TelemetryProtocolTest, SendFrameMaxPayload) {
    EXPECT_CALL(mock_uart, init(_))
        .WillOnce(Return(hal::Status::OK));
    EXPECT_CALL(mock_uart, transmit(_, 68, 1000))  // SOF(1)+LEN(1)+64+CRC(2) = 68
        .WillOnce(Return(hal::Status::OK));

    std::array<uint8_t, drivers::TelemetryProtocol::MAX_PAYLOAD> payload{};
    payload.fill(0xFF);

    drivers::TelemetryProtocol proto(mock_uart);
    ASSERT_TRUE(proto.init());
    EXPECT_TRUE(proto.send_frame(payload.data(), payload.size()));
}

// Edge-case Test 8: consecutive send_frame calls both succeed
TEST_F(TelemetryProtocolTest, ConsecutiveSendFrame) {
    EXPECT_CALL(mock_uart, init(_))
        .WillOnce(Return(hal::Status::OK));
    EXPECT_CALL(mock_uart, transmit(_, _, 1000))
        .Times(2)
        .WillRepeatedly(Return(hal::Status::OK));

    const uint8_t payload[] = {0x01, 0x02};

    drivers::TelemetryProtocol proto(mock_uart);
    ASSERT_TRUE(proto.init());
    EXPECT_TRUE(proto.send_frame(payload, sizeof(payload)));
    EXPECT_TRUE(proto.send_frame(payload, sizeof(payload)));
}

// Edge-case Test 9: init fails → send_frame returns false
TEST_F(TelemetryProtocolTest, SendFrameFailsWhenInitFails) {
    // 1. Set ALL expectations first
    EXPECT_CALL(mock_uart, init(_))
        .WillOnce(Return(hal::Status::HW_ERROR));
        
    EXPECT_CALL(mock_uart, transmit(_, _, _))
        .Times(0); // Ensures that it is never transmitted if init failed

    // 2. Run the production code
    drivers::TelemetryProtocol proto(mock_uart);
    EXPECT_FALSE(proto.init()); 
    
    const uint8_t payload[] = {0x01};
    EXPECT_FALSE(proto.send_frame(payload, sizeof(payload)));
}